apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    repoURL: https://github.com/hakobmkoyan771/infra.git
    path: Applications
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
