apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
spec:
  destination:
    name: in-cluster
    namespace: applications
  project: default
  source:
    repoURL: https://github.com/hakobmkoyan771/infra.git
    path: infra/Services
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
